### ISSUE TITLE
Add more app uses in readme ( ͡° ͜ʖ ͡°)

### ISSUE THREAD

**Issue by ghazzor** [LukeNeedham/Vibrator#3]
( ͡° ͜ʖ ͡°)

**Comment by LukeNeedham** [comment]
Good suggestion. I've added more usages to this file: https://github.com/LukeNeedham/Vibrator/blob/main/docs/AdditionalUses.md

And added a link to the full list in the readme

**Comment by ghazzor** [comment]
Nice job bro

**Comment by inson1** [comment]
@LukeNeedham what about solving world hunger?

**Comment by LukeNeedham** [comment]
Unfortunately Vibrator can't do that. Maybe in the next update 🤔
